### ISSUE TITLE
What happens when clicking on village level from national level is not clear

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2#138]
Should it be possible?

Should it pick a village at random?

**Comment by catcad** [comment]
If relatively easy to implement I would suggest to go to a random mapped off-grid cluster - but I am not sure how easy that is because then also the state level would probably need to be adjusted to that respective random state?

**Comment by Bachibouzouk** [comment]
It is ok and follows the logic of being able to get a random state assigned when clicking on the state button as requested in #173. In this case we can simply select a random state among the states which have village clusters, then select a random village within the largest villages to show

**Comment by catcad** [comment]
Would be perfect as you suggest.
