### ISSUE TITLE
Wrong grid color in Nasawara

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2#162]
Instead of the red colors, the grid appears in blue in Nasarawa

![grafik](https://user-images.githubusercontent.com/33006916/75141615-a004d600-56f1-11ea-98f7-f653e747fba4.png)

**Comment by christian-rli** [comment]
must be a tileserver error. working on it.

**Comment by christian-rli** [comment]
It was a typo in the data. I fixed in on the tileserver. It's downwards-compatible (so it's working right now), but i'll fix the typo in this project as well, so everything is correct.

**Comment by christian-rli** [comment]
@catcad you might have to delete your cache in firefox, so the new data are loaded. I had to (firefox - settings - privacy - Cookies and Website-Data... delete cache data)

**Comment by christian-rli** [comment]
Closed in #164
