### ISSUE TITLE
National view: Information display in the bottom left does not correspond to correct state information

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2#165]
e.g. some fully mapped and grid-tracked states are listed as not mapped/tracked.

**Comment by christian-rli** [comment]
Note to self: update the responsible geojson. (automate process if possible)

**Comment by christian-rli** [comment]
Sorry @Bachibouzouk I accidentally pushed to dev. Commit adds a new geojson file for states availability, fixing this issue.
