### ISSUE TITLE
State level: Populated areas should only be visible for selected states 

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2#171]
After activating populated areas in one state, then changing to another state and activating the populated areas, the others are still activated. They should become invisible again, only showing clusters in the selected state.
May also be true for off-grid clusters (not checked)?

**Comment by Bachibouzouk** [comment]
@christian-rli could this be due to this [here](https://github.com/rl-institut/NESP2/blob/922d66bad22e49cb314ae0118d75df4c8c4d3936/app/static/js/sidebar.js#L365)?

**Comment by christian-rli** [comment]
> @christian-rli could this be due to this [here](https://github.com/rl-institut/NESP2/blob/922d66bad22e49cb314ae0118d75df4c8c4d3936/app/static/js/sidebar.js#L365)?

That function did have (or was at least supposed to have) the effect of hiding previously selected state clusters. I believe as of now, there is no function there anymore. It would need to be rewritten anyway. The old layer needs to be removed before/at the time when the new selected state is set, otherwise it won't remember which layer was selected before.

**Comment by Bachibouzouk** [comment]
> It would need to be rewritten anyway.

Something along the lines of `update_grid_layer` or `update_selected_state_pbf`, I presume?

**Comment by catcad** [comment]
here you can see the issue on the mapped settlements- Kano was selected first (bottom right), then Kaduna is selected and we still see the clusters in Kano:
![grafik](https://user-images.githubusercontent.com/33006916/75280116-22ce8380-580d-11ea-850e-5c5eaebf24cc.png)
For the grid the problem does not occur, only for both cluster types. Is that because the grid comes from individual state-level files? Would that be a solution for the clusters as well?

**Comment by christian-rli** [comment]
Layers just need to be removed before the selection of the new state is stored in the variable. Commit https://github.com/rl-institut/NESP2/commit/17d7c5708ab91cbe9fa761d808feeea277f7600e does that
