### ISSUE TITLE
we need Logos and text on the bottom of the side bar

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2#177]
We need to include a text (“Provided with the financial support of” Font: Arial or Helvetica) above the EU and German Cooperation logo and we need to adjust the ratio between the GIZ logo and the other two logos. 1:0.8 as this: 
![grafik](https://user-images.githubusercontent.com/33006916/75237138-26d3b480-57bf-11ea-924e-12b859a317f5.png)
The result should look similar to this: 
![grafik](https://user-images.githubusercontent.com/33006916/75237326-74502180-57bf-11ea-9115-39f8f22bd321.png)

**Comment by Bachibouzouk** [comment]
The guidelines from GIZ would be more easily implemented (for websites) if they would provide the ratio bewteen the two logo images' (.png) heights instead of ratio of elements with the logo images (mesured with h and 0.8*h). A typical workflow that comes to my mind : having the png/svg images available for download on GIZ website with by default the correct ratio 8:10 implemented and a guideline specifying that if the images size are changed, one has to make sure that the ratio between the heights (which is not necessarily 8:10, let;s call it r = h_a/h_b) is conserved. I can make a drawing if this is not clear

As I will have to find r to make sure the 8:10 rule is respected, what I suggest is that GIZ provide this value of r as well as well formated logos in the future to their project partners (this will likely save GIZ time too :))

**Comment by Bachibouzouk** [comment]
```
def compute_giz_log_height(h_igc, golden_giz_ratio=0.8):
    """Compute the height of the giz logo with respect to the giz-coop logo height

    :param h_igc: the height of the image of giz-coop
    :param golden_giz_ratio: the ratio between the height from bottom of "i" until top the
        dot of the "i" in the giz logo and the height between the top of the "g" and the bottom
        of the "c" in the giz cooperation logo
    :return: the height of the giz logo respecting the golden_giz_ratio with the same units as h_igc
    """
    # ratio element giz-coop (element size in px/image size in px)
    # the element height is defined as the height between the top of the "g" and the bottom
    # of the "c" in the giz cooperation logo
    r_egc = 196.6 / 896

    # ratio element giz (element size in px/image size in px)
    # the element height is defined as the height from bottom of "i" until top the
    # dot of the "i" in the giz logo
    r_eg = 234.63 / 780

    # height of the element within the giz cooperation logo
    h_egc = h_igc * r_egc

    # height the element within the giz logo
    h_eg = golden_giz_ratio * h_egc

    # height of the giz logo
    h_ig = h_eg / r_eg

    return h_ig
```

**Comment by catcad** [comment]
Can you please redo this push and only push it again after the styling/design is done?

**Comment by Bachibouzouk** [comment]
It is at the bottom of the sidebar on my browser

**Comment by Bachibouzouk** [comment]
What is wrong with the styling in your browser?

**Comment by Bachibouzouk** [comment]
> Can you please redo this push and only push it again after the styling/design is done?

What do you mean by "redo this push"?

**Comment by catcad** [comment]
Sorry, I meant undo for the moment. Until the style/sizing is done (e.g. Font and colour Nigeria SE4ALL).
In my browser it looks like this: 
![grafik](https://user-images.githubusercontent.com/33006916/75389984-c9875280-58e7-11ea-8c47-f4646fe6386d.png)

**Comment by Bachibouzouk** [comment]
Oh ok, in mine it was like this
![Screenshot from 2020-02-26 22-43-36](https://user-images.githubusercontent.com/4399407/75390974-8ded8800-58e9-11ea-95a9-23b7a88b1bdc.png)

**Comment by Bachibouzouk** [comment]
Provided that :
giz cooperation logo height x width (pixel) : 896 x 1445
giz logo height x width (pixel) : 780 x 1481 

if on the website the giz cooperation image height is given by h_gc, then the height h_g of the giz logo which satisfies the giz_golden_ratio is given by 0.583 h_gc (h_g = 0.583 h_gc)

if on the website the giz cooperation image width is given by w_gc, then the width w_g of the giz logo which satisfies the giz_golden_ratio is given by 0.687 w_gc (w_g = 0.687 w_gc)
