### ISSUE TITLE
design change of state name in National view bottom left

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2#185]
The black text on the dark grey background does not look good.
One suggestion is to make it the green colour (29/208/205) or the other option would be a green background box and white text. Maybe we can get Bryans opinion here?
![grafik](https://user-images.githubusercontent.com/33006916/75384130-e4ed6000-58dd-11ea-9f4c-c6d9c5327925.png)

**Comment by Bachibouzouk** [comment]
I will not take decision on that, I will implement what will be decided
