### ISSUE TITLE
There is white space below the map when the funnel is active

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/NESP2#200]
When the funnel is active, there is an extra dropdown. Because there is not enough space on the screen for all the sidebar elements, it pushes down the logos. Because the map only has a height of 100vh, white space builds up below it.

![nesp2_map_space_below](https://user-images.githubusercontent.com/33999424/75897537-ffbd5880-5e38-11ea-8f4e-6f1959d47823.png)

**Comment by Bachibouzouk** [comment]
Could it be solved with a minimum height of the map?

**Comment by bmlancien** [comment]
> Could it be solved with a minimum height of the map?

I don't know if it's a good idea to have a map which is higher than the screen. I would not expect to scroll when using a map

**Comment by Bachibouzouk** [comment]
@bmlancien  if you write "Fix #<number of the issue>" in your PR, it closed the issue automatically when the PR is merged :)

**Comment by Bachibouzouk** [comment]
Closed via #201
