### ISSUE TITLE
There is no "Getting started" instructions

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2#22]
This is helpful for new comers on the repository if they don't have to figure out how to use your code. 

It could typically be added to the readme :)

**Comment by Bachibouzouk** [comment]
There are but not for master, which is the default branch. You can change the default branch to `dev`, so that people landing here get the latest changes (then move back to master after)

**Comment by christian-rli** [comment]
I changed the default branch to dev :)
