### ISSUE TITLE
Font of NIGERIA SE4ALL is different from website

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#223]
webmap: ![webmap](https://user-images.githubusercontent.com/42000429/76841973-d4c00500-6839-11ea-88f6-d80acedf11c1.jpg)
correct (website): ![correct(website)](https://user-images.githubusercontent.com/42000429/76841980-d7baf580-6839-11ea-8449-cf7f1ee437dc.jpg)

**Comment by Bachibouzouk** [comment]
@bmlancien

**Comment by Bachibouzouk** [comment]
Closed by #245
