### ISSUE TITLE
Null values in database aren't filtered as 50+km

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#225]
![image001](https://user-images.githubusercontent.com/42000429/76952713-ce9b5880-690d-11ea-92e5-f11b06aea30a.jpg)

**Comment by Bachibouzouk** [comment]
The PR closed this issue right @christian-rli ?

**Comment by christian-rli** [comment]
> The PR closed this issue right @christian-rli ?

Yes, thank you. Forgot to close!
