### ISSUE TITLE
Legends should have a nicer design

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2#264]
The top left box's html content is defined in map.js ([here](https://github.com/rl-institut/NESP2/blob/3ee14100000c08de5b4e00059413a20d09c3a6e0/app/static/js/map.js#L92)), hier is a summary : 
```
var control_content = '<h4 class="selection_detail_header">' + stateName + '</h4>' +
      '<table class="selection_detail">' +
      '<tr><td align="right"><b>Grid Tracking</b>:</td><td>' + avail.gridTracking + '</td></tr>' +
      '<tr><td align="right"><b>Remote Mapping</b>:</td><td>' + avail.remoteMapping + '</td></tr>' +
      '<tr><td align="right"><b>Field Surveys</b>:</td><td>' + avail.Surveying + '</td></tr>' +
      '</table>';
```

The icons have the class `state_info__img`

The lower left box's content is also defined in map.js ([here](https://github.com/rl-institut/NESP2/blob/3ee14100000c08de5b4e00059413a20d09c3a6e0/app/static/js/map.js#L138))

The lower right box's content has the classes `map-legend` and `map-legend-grid`

**Comment by bmlancien** [comment]
Something like this?

![NESP2_Legends](https://user-images.githubusercontent.com/33999424/77634737-b81a8000-6f51-11ea-99c5-70594ebcf963.png)
