### ISSUE TITLE
Filter options are sometimes not logical

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2#282]
- [x] Distance to grid : make minimum selection 0-1km (8960423b3756928ef278dd4ce48b927c26564471)
- [x] Build-up ratio instead of  build-up density (d2ccb35c8772779f4293cc112fe48932a18af161)
- [ ] Building-max-value responsiveness across states (sometimes the max value is way too high, value up to 10,000 not useful for some states (e.g. Kogi))
- [x] Area: max values are really big, which happens in larger clusters, e.g. capital regions, set to area filter >200km² (0a3bf8d88a58fb089055313e32828ef1b2c30a63)
- [x] "number of sites: X settlements out of Y" at the top of the filter section (63e57da52a12937a15cdbc4ceb9c71a2d115b6ae)
- [x] Sort RMS clusters by building counts (d42fc0ea30838aa0acc38195248d9a3a07598b54)
- [x] disable filter functions in states where it is not available
- [x] Filter for distance to grid should not be able to go lower than 5km for RMS, as they are offgrid by definition. (c2997161bd148fe6daa6e4623596d9647f1b79c0)
- [x] Check if there is an easy way to update x in x/y selected settlements @christian-rli 
- [x] Set periodic boundary conditions for settlements (7a05044d06a55d31a22816e3dd89f79edfd58da2)
- [x] Add an info icon for some filter options (e30ee5a502e4c190f4aac4aa19241d374cefd311)

**Comment by Bachibouzouk** [comment]
@christian-rli - can you manage the rest on the branch `fix/filter`?

**Comment by christian-rli** [comment]
There is no easy way to update x in x/y selected settlements. Creating a new issue for this (#286 ). Info is updated with cluster id and array of clusters. Finding the right place to refresh the value is tricky.  Also, things that need to be considered for this: define behaviour if no cluster is selected before and/or after resetting the filter.
