### ISSUE TITLE
Some miscellaneous feedbacks are not yet implemented

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2#284]
- [x] Zoom level minimum on state level (b5f3e96a25f2e001e663ba9281c0aabbcba0b80c) 
 
- [x] Grid is still shown even after deactivating it (2a9c8226e0e3d039b7859ee0c17340830f34400a)

## Esri map
- [x] set the native zoom level so that we can always see the image (ac4f4df71dcc8272f54b9d80e6f4557635c2db76)
- [x] is bing imagery on option? Not really, see comments below.

**Comment by Bachibouzouk** [comment]
@christian-rli - can you manage the rest on the branch `fix/misc`?

**Comment by christian-rli** [comment]
Using Bing imagery is allowed under conditions described in the following document: http://dev.virtualearth.net/REST/V1/Imagery/Metadata/RoadOnDemand?output=json&include=ImageryProviders&key=BingMapsKey
I'll have a look and see how easy implementation will be.

**Comment by christian-rli** [comment]
Okay, so there is a lot of legal foo in the way. https://www.microsoft.com/en-us/maps/product 

Using tiles with a hardcoded URL is not allowed. We would need an account granting us a bing maps id. Unknown side-effects. Before doing this, we should check in again and see whether it's important to them. Esri is working now, so maybe it's not so relevant anymore.
