### ISSUE TITLE
Minimum of distance to the grid should be 0

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2#305]

**Comment by Bachibouzouk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Distance to the grid](https://trello.com/c/XqedrvZ9/53-distance-to-the-grid)

**Comment by Bachibouzouk** [comment]
@christian-rli - do you think you can take care of it as it is related to the filters?

**Comment by christian-rli** [comment]
i'm on it.
