### ISSUE TITLE
Automated script for database update is missing

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2#310]
Maybe this was already solved, would be nice to have the info here for completness :)

**Comment by Bachibouzouk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automated update script/option for database updates to the tiles for the webmap is required.](https://trello.com/c/Wio0kJop/58-automated-update-script-option-for-database-updates-to-the-tiles-for-the-webmap-is-required)

**Comment by Bachibouzouk** [comment]
@christian-rli ?

**Comment by christian-rli** [comment]
I uploaded the files I created for server updates. These have been adapted on the server side by the admin. I could not keep track of all changes. Alex may update these here.

**Comment by christian-rli** [comment]
Closed in #317
