### ISSUE TITLE
possible sql injection

### ISSUE THREAD

**Issue by fzimmermann89** [rl-institut/NESP2#334]
Hi,

just passing by, but noticed (at least one) sql injection issue in
https://github.com/rl-institut/NESP2/blob/a82e6ce7ae6e81b2a1e08a31858399839c0fdf81/app/database.py#L66
user-controlled data is used without escaping in a raw sql query.  I suggest either to use the orm layer, or maybe one of 
```
table = Table('table', metadata, autoload = True, autoload_with = engine)
s=table.select().where(Column('blub') == usercontrolled1).where(Column('muh') == usercontrolled2)
```
or 
```
filter=['blub = :value1', 'blub2 = :value1'] 
values={'value1':usercontrolled1,'value2':usercontrolled2}
sql = 'select * from table where' + 'and'.join(filter)
result = connection.execute(sql, **values)
``` 
should make sqlalchemy escape the input.

The severity of this issue depends on the sql server configuration, I don't want to set up a local test environment

**Comment by Bachibouzouk** [comment]
Hi @fzimmermann89 - thanks for pointing it out, I think this is the only place where user input is used. I will implement one of your suggestions!

**Comment by Bachibouzouk** [comment]
By looking at the code again, I realize this function was only used during development (to query filtered subsets from the database), but now we query all settlements of a state and apply fliters client side, therefore there is no risk of SQL injection in this case.

I will still modify the code to prevent that it is used in the future

**Comment by fzimmermann89** [comment]
>I will implement one of your suggestions!

great, you might want to check if they actually fix the issue :)

> therefore there is no risk of SQL injection in this case.

I might disagree:
```
wget "http://se4allwebpage.westeurope.cloudapp.azure.com/csv-export?state=Edo&cluster_type=ogcluster&ogmin_area=0;SELECT PG_SLEEP(10)--&ogmax_area=10&ogmindtg=0&ogmaxdtg=100&ogminb=0&ogmaxb=10000&ogminbfp=0&ogmaxbfp=100"
```
takes 10s... 
```
wget "http://se4allwebpage.westeurope.cloudapp.azure.com/csv-export?state=Edo&cluster_type=ogcluster&ogmin_area=0;SELECT PG_SLEEP(5)--&ogmax_area=10&ogmindtg=0&ogmaxdtg=100&ogminb=0&ogmaxb=10000&ogminbfp=0&ogmaxbfp=100"
```
takes 5s.

--> The PG_SLEEP is executed 

I don't know where the production deployment is at, but ```http://se4allwebpage.westeurope.cloudapp.azure.com/``` is vulnerable.

**Comment by Bachibouzouk** [comment]
I had the mask `*.js` in my pycharm global search function... therefore I didn't find the other occurrences of the function been executed and I wrongfully thought it would only be called when clicking on a state, forgetting the csv export!

I unfortunately don't "speak" SQL, so thanks for your query, it will help me to see if the PG_SLEEP is escaped :)

**Comment by Bachibouzouk** [comment]
@fzimmermann89 - now the sql injections should not be possible anymore (I tested with your example)

**Comment by fzimmermann89** [comment]
👍
