### ISSUE TITLE
Levels: National level: Pop-up

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2#47]
On the national level there shall be for each state a pop-up containing

- state name

- length of tracked grid

- number of buildings remotely mapped

- number of sites which were surveyed in detail

In addition, in the pop-up shall be a link with "Go to state" - changing the view to the state level of that respective state - the same effect as if selected in the drop down menu under the state level.

**Comment by christian-rli** [comment]
This was discussed and discarded in a telco.
