### ISSUE TITLE
Missing data on tileserver

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#5]
In this issue, create a checklist of files to upload based on #3 and #4 . The list may look like this:
- [x] Item 1 
- [ ] Item 2 (preliminary)
- [ ] Item 3

Then upload all items, checking the boxes of that list. If at first we have to wait for actual data it might make sense to create a preliminary data set in order to be able to test functionality on it. If preliminary data are available, just state so (brackets behind the item). You may edit the list in this comment to turn it into the actual list.

**Comment by christian-rli** [comment]
Data on the tileserver have been updated. Now available are clusters and off grid clusters for every state with availability and separate layers each for centroids:

off-grid clusters with layername 'OGClusters': 
nesp2_state_offgrid_clusters_abia
nesp2_state_offgrid_clusters_anambra
nesp2_state_offgrid_clusters_bauchi
nesp2_state_offgrid_clusters_benue
nesp2_state_offgrid_clusters_delta
nesp2_state_offgrid_clusters_edo
nesp2_state_offgrid_clusters_ekiti
nesp2_state_offgrid_clusters_enugu
nesp2_state_offgrid_clusters_federal_capital_territory
nesp2_state_offgrid_clusters_jigawa
nesp2_state_offgrid_clusters_kaduna
nesp2_state_offgrid_clusters_kano
nesp2_state_offgrid_clusters_katsina
nesp2_state_offgrid_clusters_kebbi
nesp2_state_offgrid_clusters_kogi
nesp2_state_offgrid_clusters_kwara
nesp2_state_offgrid_clusters_nasarawa
nesp2_state_offgrid_clusters_niger
nesp2_state_offgrid_clusters_ogun
nesp2_state_offgrid_clusters_ondo
nesp2_state_offgrid_clusters_osun
nesp2_state_offgrid_clusters_oyo
nesp2_state_offgrid_clusters_plateau
nesp2_state_offgrid_clusters_sokoto
nesp2_state_offgrid_clusters_yobe
nesp2_state_offgrid_clusters_zamfara

centroids of off-grid clusters with layername 'OGCluster_centroids': 
nesp2_state_offgrid_cluster_centroids_abia
nesp2_state_offgrid_cluster_centroids_anambra
nesp2_state_offgrid_cluster_centroids_benue
nesp2_state_offgrid_cluster_centroids_delta
nesp2_state_offgrid_cluster_centroids_edo
nesp2_state_offgrid_cluster_centroids_ekiti
nesp2_state_offgrid_cluster_centroids_enugu
nesp2_state_offgrid_cluster_centroids_federal_capital_territory
nesp2_state_offgrid_cluster_centroids_jigawa
nesp2_state_offgrid_cluster_centroids_kaduna
nesp2_state_offgrid_cluster_centroids_kano
nesp2_state_offgrid_cluster_centroids_katsina
nesp2_state_offgrid_cluster_centroids_kebbi
nesp2_state_offgrid_cluster_centroids_kogi
nesp2_state_offgrid_cluster_centroids_kwara
nesp2_state_offgrid_cluster_centroids_nasarawa
nesp2_state_offgrid_cluster_centroids_niger
nesp2_state_offgrid_cluster_centroids_ogun
nesp2_state_offgrid_cluster_centroids_osun
nesp2_state_offgrid_cluster_centroids_oyo
nesp2_state_offgrid_cluster_centroids_plateau
nesp2_state_offgrid_cluster_centroids_sokoto
nesp2_state_offgrid_cluster_centroids_yobe
nesp2_state_offgrid_cluster_centroids_zamfara

Populated area clusters with layername 'regions': 
nesp2_state_clusters_abia
nesp2_state_clusters_adamawa
nesp2_state_clusters_akwa_ibom
nesp2_state_clusters_anambra
nesp2_state_clusters_bauchi
nesp2_state_clusters_bayelsa
nesp2_state_clusters_benue
nesp2_state_clusters_borno
nesp2_state_clusters_cross_river
nesp2_state_clusters_delta
nesp2_state_clusters_ebonyi
nesp2_state_clusters_edo
nesp2_state_clusters_ekiti
nesp2_state_clusters_enugu
nesp2_state_clusters_federal_capital_territory
nesp2_state_clusters_gombe
nesp2_state_clusters_imo
nesp2_state_clusters_jigawa
nesp2_state_clusters_kaduna
nesp2_state_clusters_kano
nesp2_state_clusters_katsina
nesp2_state_clusters_kebbi
nesp2_state_clusters_kogi
nesp2_state_clusters_kwara
nesp2_state_clusters_lagos
nesp2_state_clusters_nasarawa
nesp2_state_clusters_niger
nesp2_state_clusters_ogun
nesp2_state_clusters_ondo
nesp2_state_clusters_osun
nesp2_state_clusters_oyo
nesp2_state_clusters_plateau
nesp2_state_clusters_rivers
nesp2_state_clusters_sokoto
nesp2_state_clusters_taraba
nesp2_state_clusters_yobe
nesp2_state_clusters_zamfara

Centroids of populated area clusters with layername 'region_centroids': 
nesp2_state_cluster_centroids_abia
nesp2_state_cluster_centroids_adamawa
nesp2_state_cluster_centroids_akwa_ibom
nesp2_state_cluster_centroids_anambra
nesp2_state_cluster_centroids_bauchi
nesp2_state_cluster_centroids_bayelsa
nesp2_state_cluster_centroids_benue
nesp2_state_cluster_centroids_borno
nesp2_state_cluster_centroids_cross_river
nesp2_state_cluster_centroids_delta
nesp2_state_cluster_centroids_ebonyi
nesp2_state_cluster_centroids_edo
nesp2_state_cluster_centroids_ekiti
nesp2_state_cluster_centroids_enugu
nesp2_state_cluster_centroids_federal_capital_territory
nesp2_state_cluster_centroids_gombe
nesp2_state_cluster_centroids_imo
nesp2_state_cluster_centroids_jigawa
nesp2_state_cluster_centroids_kaduna
nesp2_state_cluster_centroids_kano
nesp2_state_cluster_centroids_katsina
nesp2_state_cluster_centroids_kebbi
nesp2_state_cluster_centroids_kogi
nesp2_state_cluster_centroids_kwara
nesp2_state_cluster_centroids_lagos
nesp2_state_cluster_centroids_nasarawa
nesp2_state_cluster_centroids_niger
nesp2_state_cluster_centroids_ogun
nesp2_state_cluster_centroids_ondo
nesp2_state_cluster_centroids_osun
nesp2_state_cluster_centroids_oyo
nesp2_state_cluster_centroids_plateau
nesp2_state_cluster_centroids_rivers
nesp2_state_cluster_centroids_sokoto
nesp2_state_cluster_centroids_taraba
nesp2_state_cluster_centroids_yobe
nesp2_state_cluster_centroids_zamfara

**Comment by Bachibouzouk** [comment]
Can this be closed @christian-rli ?

**Comment by christian-rli** [comment]
Yeah. It's outdated :)
