### ISSUE TITLE
Missing Flask functions to serve geojson from database

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#56]
Create functions that connect to the se4all postgresql database and that serve the data there as geojson to the webmap. The database is not public yet. I will send you the access details via mail @Bachibouzouk . 

server: `se4allpostgres.postgres.database.azure.com`
database: `se4all_nigeria`

As a sample you may use the materialized view `distribution_line_all_mv` in the schema `se4all`.

Thank you :)

**Comment by Bachibouzouk** [comment]
Not needed since #221
