### ISSUE TITLE
Missing Grid legend

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#63]
create a legend for the grid that shows on the bottom left in state view when the layer is activated and disappears when it's not. The layer "info" is a good reference for this. (var info = L.control({position: 'bottomleft'}); ...)

make a small image with a thick line and the "33 kV" and another one with a thinner line for "11 kV" like displayed on the map.

create a legend for the grid that shows on the bottom left in state view when the layer is activated and disappears when it's not. The layer "info" is a good reference for this:
 
var info = L.control({position: 'bottomleft'});

make a small image with a thick line and label for 33kv and another one with a thinner line for 11kv like displayed on the map. For inspiration see https://github.com/rl-institut/Zambia_OG/tree/master/data/legend

**Comment by Bachibouzouk** [comment]
This is implemented now
