### ISSUE TITLE
Incomplete information in State-hover-info

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#64]
Needs:
- [x] name of state
- [ ] length of tracked grid
- [ ] number of buildings remotely mapped
- [ ] number of sites which were surveyed in detail

draw info from database and update in served tiles. If you want to help @Bachibouzouk draw the information and give them to me in a list.

**Comment by Bachibouzouk** [comment]
@yelsre - from which of the db table/view should I extract this information for a given state?

**Comment by yelsre** [comment]
> @yelsre - from which of the db table/view should I extract this information for a given state?

please refer to my email!

**Comment by Bachibouzouk** [comment]
@yelsre - you suggested that this information might not be relevant at all to display. If this is the case, the issue can be closed then :)

**Comment by Bachibouzouk** [comment]
Ollie said this information is not relevant to be displayed
