### ISSUE TITLE
Create Download Button for filtered selection

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2#69]
Create a download button that lets the user download the filtered clusters from the database (filter options are taken as query parameters).

**Comment by Bachibouzouk** [comment]
As geojson I presume?

**Comment by Bachibouzouk** [comment]
@christian-rli ?

**Comment by christian-rli** [comment]
Yes, as geojson or csv (without geoinformation in case of the latter). 

off-grid-clusters have the following columns:
cluster_offgrid_id, area_km2, building_count, large_building_count, percentage_large_building, building_area_km2, building_count_density_perkm2, percentage_building_area, grid_dist_km

cluster_all:
cluster_all_id, fid, area_km2, grid_dist_km

**Comment by Bachibouzouk** [comment]
The follow up of this issue is in #96
